#!/bin/bash

echo "🧪 Model Selection Test Suite"
echo "============================="
echo ""
echo "Test these messages in Slack to verify all patterns work:"
echo ""

echo "1️⃣ SLASH COMMANDS"
echo "─────────────────"
echo "@claude /model advanced explain how neural networks work"
echo "@claude /model fast what time is it?"
echo "@claude /model 3.7 test latest features"
echo "@claude /mode smart analyze this data"
echo ""

echo "2️⃣ NAMED PRESETS"
echo "────────────────"
echo "@claude advanced mode write a business plan"
echo "@claude fast mode quick calculation: 15 * 23"
echo "@claude balanced mode help me debug this"
echo "@claude smart mode solve this algorithm"
echo "@claude latest mode what's new in AI?"
echo ""

echo "3️⃣ NATURAL LANGUAGE"
echo "───────────────────"
echo "@claude using sonnet-4 create documentation"
echo "@claude with advanced model analyze trends"
echo "@claude model: 3.5 summarize this article"
echo ""

echo "4️⃣ SHORT ALIASES"
echo "────────────────"
echo "@claude /model 4 complex analysis"
echo "@claude /model 3.5 quick response"
echo "@claude /model 3.7 new features test"
echo ""

echo "5️⃣ AUTO-SELECTION"
echo "─────────────────"
echo "@claude write a comprehensive guide about Docker"
echo "@claude create a detailed technical specification"
echo "@claude give me a thorough analysis of this code"
echo ""

echo "6️⃣ EDGE CASES"
echo "─────────────"
echo "@claude /MODEL ADVANCED uppercase test"
echo "@claude /model invalidmodel fallback test"
echo "@claude mixed /model 4 and detailed request"
echo ""

echo "📊 What to Check:"
echo "────────────────"
echo "1. Bot shows model in placeholder: '(using Sonnet 4)'"
echo "2. GitHub Actions uses correct model parameter"
echo "3. Invalid models fall back to default (3.5)"
echo "4. Auto-selection works for complex requests"
echo ""

echo "🔍 Monitoring:"
echo "─────────────"
echo "- Cloudflare logs: wrangler tail"
echo "- GitHub Actions: Check workflow runs"
echo "- Look for 'Model extracted from message' in logs"
echo ""

echo "✅ Expected Models:"
echo "──────────────────"
echo "advanced/smart/deep/4 → claude-sonnet-4-20250514"
echo "fast/balanced/quick/3.5 → claude-3-5-sonnet-20241022"
echo "latest/newest/3.7 → claude-3-7-sonnet-20250219"