name = "claude-slack-bot"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "claude-slack-bot"

[[kv_namespaces]]
binding = "THREAD_CACHE"
id = "43889703c89e4e1696ac47b11eb70c0d"
preview_id = "26ffe07d64f344a8a2bb78df08de57fb"

[vars]
GITHUB_OWNER = "jerryzhao173985"
GITHUB_REPO = "claude-slack-bot"
GITHUB_WORKFLOW_FILE = "claude-code-processor-best.yml"
GITHUB_USERNAME = "jerryzhao173985"

# Secrets to be set with wrangler secret put:
# SLACK_SIGNING_SECRET
# SLACK_BOT_TOKEN
# GITHUB_TOKEN