name: Claude Code Processor Hybrid

on:
  workflow_dispatch:
    inputs:
      question:
        description: "User question from Slack"
        required: true
        type: string
      mcp_tools:
        description: "Comma-separated list of MCP tools to enable"
        required: false
        type: string
        default: "slack"
      slack_channel:
        description: "Slack channel ID"
        required: true
        type: string
      slack_ts:
        description: "Slack message timestamp to update"
        required: true
        type: string
      slack_thread_ts:
        description: "Slack thread timestamp"
        required: false
        type: string
      system_prompt:
        description: "System prompt with thread context"
        required: false
        type: string

jobs:
  run-claude:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Debug inputs
        run: |
          echo "Channel: ${{ github.event.inputs.slack_channel }}"
          echo "Message TS to update: ${{ github.event.inputs.slack_ts }}"
          echo "Thread TS: ${{ github.event.inputs.slack_thread_ts }}"
      
      - name: Create response script
        run: |
          cat > update_slack.sh << 'EOF'
          #!/bin/bash
          CHANNEL="${1}"
          TS="${2}"
          TEXT="${3}"
          
          # Try to update the message
          RESPONSE=$(curl -s -X POST https://slack.com/api/chat.update \
            -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{
              \"channel\": \"${CHANNEL}\",
              \"ts\": \"${TS}\",
              \"text\": \"${TEXT}\"
            }")
          
          # Check if update was successful
          if echo "$RESPONSE" | jq -e '.ok == true' > /dev/null; then
            echo "Message updated successfully"
          else
            echo "Update failed, posting as reply"
            curl -X POST https://slack.com/api/chat.postMessage \
              -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" \
              -H "Content-Type: application/json" \
              -d "{
                \"channel\": \"${CHANNEL}\",
                \"thread_ts\": \"${TS}\",
                \"text\": \"${TEXT}\"
              }"
          fi
          EOF
          chmod +x update_slack.sh
      
      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-base-action@beta
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: ${{ github.event.inputs.slack_channel }}
          SLACK_TS: ${{ github.event.inputs.slack_ts }}
        with:
          prompt: |
            You are a helpful Slack bot assistant. Answer the following question concisely:
            
            ${{ github.event.inputs.question }}
            
            After providing your answer, save it to a file called 'response.txt' using the Write tool.
            Your response should be helpful, clear, and directly address the user's question.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic_model: claude-3-7-sonnet-20250219
          allowed_tools: "Write,Read,Bash,WebSearch"
          max_turns: 10
          claude_env: |
            ANTHROPIC_PROMPT_CACHING=1
      
      - name: Update Slack with response
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          # Read Claude's response
          if [ -f "response.txt" ]; then
            RESPONSE=$(cat response.txt | jq -Rs .)
            RESPONSE=${RESPONSE:1:-1}  # Remove quotes
          else
            RESPONSE="I've completed the task. Please check the results above."
          fi
          
          # Update Slack
          ./update_slack.sh \
            "${{ github.event.inputs.slack_channel }}" \
            "${{ github.event.inputs.slack_ts }}" \
            "$RESPONSE"