name: Claude Code Processor Update

on:
  workflow_dispatch:
    inputs:
      question:
        description: "User question from Slack"
        required: true
        type: string
      mcp_tools:
        description: "Comma-separated list of MCP tools to enable"
        required: false
        type: string
        default: "slack"
      slack_channel:
        description: "Slack channel ID"
        required: true
        type: string
      slack_ts:
        description: "Slack message timestamp to update"
        required: true
        type: string
      slack_thread_ts:
        description: "Slack thread timestamp"
        required: false
        type: string
      system_prompt:
        description: "System prompt with thread context"
        required: false
        type: string

jobs:
  run-claude:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Debug inputs
        run: |
          echo "Channel: ${{ github.event.inputs.slack_channel }}"
          echo "Message TS to update: ${{ github.event.inputs.slack_ts }}"
          echo "Thread TS: ${{ github.event.inputs.slack_thread_ts }}"
          echo "Question: ${{ github.event.inputs.question }}"
      
      - name: Run Claude Code
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            You are a helpful Slack bot assistant responding to a user question.
            
            User question: ${{ github.event.inputs.question }}
            
            IMPORTANT INSTRUCTIONS:
            1. Answer the user's question concisely and helpfully
            2. You MUST update the existing Slack message (not create a new one)
            3. Use the mcp__slack__chat_update tool with these EXACT parameters:
               - channel: "${{ github.event.inputs.slack_channel }}"
               - ts: "${{ github.event.inputs.slack_ts }}"
               - text: Your complete response
            
            The message timestamp "${{ github.event.inputs.slack_ts }}" is the placeholder message that says "Working on your request..." - you need to replace it with your answer.
            
            DO NOT use slack_post_message or slack_reply_to_thread - ONLY use chat_update.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic_model: claude-3-7-sonnet-20250219
          mcp_config: |
            {
              "mcpServers": {
                "slack": {
                  "command": "npx",
                  "args": ["-y", "@modelcontextprotocol/server-slack"],
                  "env": {
                    "SLACK_BOT_TOKEN": "${{ secrets.SLACK_BOT_TOKEN }}",
                    "SLACK_TEAM_ID": "${{ secrets.SLACK_TEAM_ID }}"
                  }
                }
              }
            }
          allowed_tools: "mcp__slack__chat_update,mcp__slack__get_channel_info,mcp__slack__get_user_info"
          max_turns: 5
          claude_env: |
            ANTHROPIC_PROMPT_CACHING=1
            CLAUDE_CODE_AUTORUN_TOOLS=true
            MCP_VERBOSE=true