name: Claude Simple Working

on:
  workflow_dispatch:
    inputs:
      question:
        description: "User question from Slack"
        required: true
        type: string
      slack_channel:
        description: "Slack channel ID"
        required: true
        type: string
      slack_ts:
        description: "Slack message timestamp (placeholder)"
        required: true
        type: string
      slack_thread_ts:
        description: "Slack thread timestamp"
        required: false
        type: string

jobs:
  respond:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Call Claude and Update Slack
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          # Create Claude API request
          cat > request.json << EOF
          {
            "model": "claude-3-5-sonnet-20241022",
            "max_tokens": 1000,
            "messages": [{
              "role": "user",
              "content": "You are a helpful Slack bot assistant. Please provide a concise, helpful response to this question: ${{ github.event.inputs.question }}"
            }]
          }
          EOF
          
          # Call Claude API
          echo "Calling Claude API..."
          CLAUDE_RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
            -H "x-api-key: $ANTHROPIC_API_KEY" \
            -H "anthropic-version: 2023-06-01" \
            -H "content-type: application/json" \
            -d @request.json)
          
          # Extract text from response
          RESPONSE_TEXT=$(echo "$CLAUDE_RESPONSE" | jq -r '.content[0].text // empty')
          
          if [ -z "$RESPONSE_TEXT" ]; then
            RESPONSE_TEXT="I encountered an error processing your request. Please try again."
            echo "Error in Claude response:"
            echo "$CLAUDE_RESPONSE"
          else
            echo "Claude responded successfully"
          fi
          
          # Prepare Slack update
          jq -n \
            --arg channel "${{ github.event.inputs.slack_channel }}" \
            --arg ts "${{ github.event.inputs.slack_ts }}" \
            --arg text "$RESPONSE_TEXT" \
            '{channel: $channel, ts: $ts, text: $text}' > slack_update.json
          
          # Update Slack message
          echo "Updating Slack message..."
          UPDATE_RESULT=$(curl -s -X POST https://slack.com/api/chat.update \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d @slack_update.json)
          
          # Check if update was successful
          if echo "$UPDATE_RESULT" | jq -e '.ok == true' > /dev/null 2>&1; then
            echo "✅ Successfully updated Slack message!"
          else
            echo "❌ Failed to update Slack message"
            echo "Error: $(echo "$UPDATE_RESULT" | jq -r '.error // "unknown"')"
            echo "Full response: $UPDATE_RESULT"
            
            # Debug info
            echo ""
            echo "Debug information:"
            echo "Channel: ${{ github.event.inputs.slack_channel }}"
            echo "Message TS: ${{ github.event.inputs.slack_ts }}"
            echo "Response length: ${#RESPONSE_TEXT}"
          fi