name: Claude Code Processor Simple Perms

on:
  workflow_dispatch:
    inputs:
      question:
        description: "User question from Slack"
        required: true
        type: string
      slack_channel:
        description: "Slack channel ID"
        required: true
        type: string
      slack_ts:
        description: "Slack message timestamp (placeholder)"
        required: true
        type: string
      slack_thread_ts:
        description: "Slack thread timestamp"
        required: false
        type: string

jobs:
  run-claude:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create outputs directory
        run: mkdir -p outputs
      
      - name: Run Claude Code with Simple Permissions
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            You are a helpful Slack bot assistant. Answer this question: ${{ github.event.inputs.question }}
            
            Save your complete response to the file: outputs/slack_response.txt
            
            Make sure your response is clear, helpful, and properly formatted for Slack.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic_model: claude-3-5-sonnet-20241022
          # Simple format mentioned in the discussion
          allowed_tools: "Bash Edit Write"
          max_turns: 10
          claude_env: |
            ANTHROPIC_PROMPT_CACHING=1
            CLAUDE_CODE_AUTORUN_TOOLS=true
      
      - name: Update Slack Message
        if: always()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          # Read the response
          if [ -f "outputs/slack_response.txt" ]; then
            echo "✅ Found response file"
            RESPONSE=$(cat outputs/slack_response.txt)
          else
            echo "❌ No response file found"
            # List any files created
            echo "Files in outputs directory:"
            ls -la outputs/ || echo "No outputs directory"
            echo "Files in current directory:"
            ls -la *.txt || echo "No txt files"
            RESPONSE="I apologize, but I couldn't save my response properly. Please check the logs."
          fi
          
          # Update Slack
          ESCAPED_RESPONSE=$(echo "$RESPONSE" | jq -Rs .)
          
          UPDATE_RESULT=$(curl -s -X POST https://slack.com/api/chat.update \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"channel\": \"${{ github.event.inputs.slack_channel }}\",
              \"ts\": \"${{ github.event.inputs.slack_ts }}\",
              \"text\": $ESCAPED_RESPONSE
            }")
          
          if echo "$UPDATE_RESULT" | jq -e '.ok == true' > /dev/null 2>&1; then
            echo "✅ Successfully updated Slack message"
          else
            echo "❌ Update failed: $(echo "$UPDATE_RESULT" | jq -r '.error')"
            # Post as reply
            curl -X POST https://slack.com/api/chat.postMessage \
              -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{
                \"channel\": \"${{ github.event.inputs.slack_channel }}\",
                \"thread_ts\": \"${{ github.event.inputs.slack_thread_ts || github.event.inputs.slack_ts }}\",
                \"text\": $ESCAPED_RESPONSE
              }"
          fi