name: Claude Code Processor Ultimate

on:
  workflow_dispatch:
    inputs:
      question:
        description: "User question from Slack"
        required: true
        type: string
      mcp_tools:
        description: "Comma-separated list of MCP tools to enable"
        required: false
        type: string
        default: "slack"
      slack_channel:
        description: "Slack channel ID"
        required: true
        type: string
      slack_ts:
        description: "Slack message timestamp (placeholder)"
        required: true
        type: string
      slack_thread_ts:
        description: "Slack thread timestamp"
        required: false
        type: string
      system_prompt:
        description: "System prompt with thread context"
        required: false
        type: string
      model:
        description: "Claude model to use"
        required: false
        type: string
        default: "claude-3-5-sonnet-20241022"

jobs:
  run-claude:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create outputs directory
        run: mkdir -p outputs
      
      - name: Run Claude Code with Proper Permissions
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            You are a helpful Slack bot assistant. A user has asked you a question in Slack.
            
            User question: ${{ github.event.inputs.question }}
            Slack channel: ${{ github.event.inputs.slack_channel }}
            Timestamp: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
            
            Please provide a helpful and concise response to the user's question.
            
            IMPORTANT STEPS TO FOLLOW IN ORDER:
            
            1. First, save this Q&A session to Notion:
               a) Search for a page titled "Claude Code" using mcp__notionApi__API-post-search
               b) If not found, create a new page titled "Claude Code" as the parent folder
               c) Create a new page under "Claude Code" with:
                  - Title: The user's question (truncated to 100 chars if needed)
                  - Content should include:
                    - Question section with the full question
                    - Answer section with your complete response
                    - Metadata section with timestamp, channel ID, and model used
               d) Use mcp__notionApi__API-post-pages and mcp__notionApi__API-post-blocks as needed
            
            2. Then, send your response to Slack:
               - Use mcp__slack__slack_reply_to_thread tool:
                 - channel_id: "${{ github.event.inputs.slack_channel }}"
                 - thread_ts: "${{ github.event.inputs.slack_thread_ts || github.event.inputs.slack_ts }}"
                 - text: Your complete response
            
            3. If Slack reply fails, save your response to: outputs/slack_response.txt
            
            Make sure to complete BOTH the Notion save AND the Slack reply.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic_model: ${{ github.event.inputs.model }}
          # Correct comma-separated format with all necessary tools including Notion
          allowed_tools: "mcp__slack__slack_list_channels,mcp__slack__slack_post_message,mcp__slack__slack_reply_to_thread,mcp__slack__slack_add_reaction,mcp__slack__slack_get_channel_history,mcp__slack__slack_get_thread_replies,mcp__slack__slack_get_users,mcp__slack__slack_get_user_profile,mcp__notionApi__API-post-search,mcp__notionApi__API-post-comments,mcp__notionApi__API-post-pages,mcp__notionApi__API-get-pages,mcp__notionApi__API-get-blocks,mcp__notionApi__API-post-blocks,mcp__notionApi__API-patch-blocks,mcp__notionApi__API-delete-blocks,mcp__notionApi__API-get-databases,mcp__notionApi__API-post-databases,mcp__notionApi__API-get-users,mcp__notionApi__API-get-comments,Write,Read,Edit,MultiEdit,Bash(echo:*),Bash(cat:*),Bash(ls:*),Glob,Grep,LS,Task,TodoRead,TodoWrite,WebSearch,WebFetch"
          mcp_config: |
            {
              "mcpServers": {
                "notionApi": {
                  "command": "npx",
                  "args": ["-y","@notionhq/notion-mcp-server"],
                  "env": { 
                    "OPENAPI_MCP_HEADERS": "{\"Authorization\":\"Bearer ${{ secrets.NOTION_KEY }}\",\"Notion-Version\":\"2022-06-28\"}"
                  }
                },
                "slack": {
                  "command": "npx",
                  "args": ["-y","@modelcontextprotocol/server-slack"],
                  "env": { 
                    "SLACK_BOT_TOKEN": "${{ secrets.SLACK_BOT_TOKEN }}",
                    "SLACK_TEAM_ID": "${{ secrets.SLACK_TEAM_ID }}" 
                  }
                },
                "github": {
                  "command": "npx",
                  "args": ["-y","@modelcontextprotocol/server-github"],
                  "env": { 
                    "GITHUB_TOKEN": "${{ secrets.GH_TOKEN }}" 
                  }
                }
              }
            }
          max_turns: 15
          claude_env: |
            ANTHROPIC_PROMPT_CACHING=1
            CLAUDE_CODE_AUTORUN_TOOLS=true
      
      - name: Update Slack if MCP failed
        if: always()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          # Check if response file was created (fallback)
          if [ -f "outputs/slack_response.txt" ]; then
            echo "Found fallback response file"
            RESPONSE=$(cat outputs/slack_response.txt)
          else
            # Check for any response in the logs
            echo "No response file found"
            RESPONSE=""
          fi
          
          # Only update if we have a response (MCP might have already handled it)
          if [ -n "$RESPONSE" ]; then
            ESCAPED_RESPONSE=$(echo "$RESPONSE" | jq -Rs .)
            
            echo "Updating Slack message with fallback..."
            UPDATE_RESULT=$(curl -s -X POST https://slack.com/api/chat.update \
              -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{
                \"channel\": \"${{ github.event.inputs.slack_channel }}\",
                \"ts\": \"${{ github.event.inputs.slack_ts }}\",
                \"text\": $ESCAPED_RESPONSE
              }")
            
            if echo "$UPDATE_RESULT" | jq -e '.ok == true' > /dev/null 2>&1; then
              echo "✅ Updated via fallback"
            else
              echo "Fallback update failed, posting as reply..."
              curl -X POST https://slack.com/api/chat.postMessage \
                -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
                -H "Content-Type: application/json" \
                -d "{
                  \"channel\": \"${{ github.event.inputs.slack_channel }}\",
                  \"thread_ts\": \"${{ github.event.inputs.slack_thread_ts || github.event.inputs.slack_ts }}\",
                  \"text\": $ESCAPED_RESPONSE
                }"
            fi
          else
            echo "No fallback needed - MCP likely handled the response"
          fi