name: Debug Notion MCP

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: "Run in test mode"
        required: false
        type: boolean
        default: true

jobs:
  debug-mcp:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Debug Environment Variables
        run: |
          echo "=== Checking NOTION_KEY ==="
          if [ -n "${{ secrets.NOTION_KEY }}" ]; then
            echo "✅ NOTION_KEY is set"
            echo "Token starts with: $(echo "${{ secrets.NOTION_KEY }}" | cut -c1-7)..."
          else
            echo "❌ NOTION_KEY is not set"
          fi
          
      - name: Test Notion API Connection
        env:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
        run: |
          echo "=== Testing Notion API ==="
          bash test-notion-token.sh
          
      - name: Generate MCP Config
        run: |
          echo "=== Generating MCP Config ==="
          cat > test-mcp-config.json <<'EOF'
          {
            "mcpServers": {
              "notionApi": {
                "command": "npx",
                "args": ["-y","@notionhq/notion-mcp-server"],
                "env": { 
                  "OPENAPI_MCP_HEADERS": "{\"Authorization\":\"Bearer ${{ secrets.NOTION_KEY }}\",\"Notion-Version\":\"2022-06-28\"}"
                }
              }
            }
          }
          EOF
          
          echo "Generated config:"
          cat test-mcp-config.json
          
          # Validate JSON
          if jq . test-mcp-config.json > /dev/null 2>&1; then
            echo "✅ Valid JSON"
          else
            echo "❌ Invalid JSON"
          fi
          
      - name: Test MCP Server Launch
        run: |
          echo "=== Testing MCP Server Launch ==="
          
          # Set the environment variable
          export OPENAPI_MCP_HEADERS="{\"Authorization\":\"Bearer ${{ secrets.NOTION_KEY }}\",\"Notion-Version\":\"2022-06-28\"}"
          
          # Try to start the server (will timeout after 5 seconds)
          timeout 5 npx -y @notionhq/notion-mcp-server || true
          
          echo "Server test completed (timeout is expected)"
          
      - name: Run Minimal Claude Code Test
        if: ${{ github.event.inputs.test_mode == 'true' }}
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            This is a debug test. Please try to use the Notion MCP tool to search for pages.
            
            Use the mcp__notionApi__API-post-search tool to search for any pages.
            
            If it works, respond with "✅ Notion MCP is working!"
            If it fails, respond with the error message you received.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic_model: "claude-3-5-sonnet-20241022"
          allowed_tools: "mcp__notionApi__API-post-search,mcp__notionApi__API-get-users,Write"
          mcp_config: |
            {
              "mcpServers": {
                "notionApi": {
                  "command": "npx",
                  "args": ["-y","@notionhq/notion-mcp-server"],
                  "env": { 
                    "OPENAPI_MCP_HEADERS": "{\"Authorization\":\"Bearer ${{ secrets.NOTION_KEY }}\",\"Notion-Version\":\"2022-06-28\"}"
                  }
                }
              }
            }
          max_turns: 3
          claude_env: |
            ANTHROPIC_PROMPT_CACHING=1
            CLAUDE_CODE_AUTORUN_TOOLS=true
            CLAUDE_CODE_THINKING=false