name: Test Notion Content Creation

on:
  workflow_dispatch:
    inputs:
      test_question:
        description: "Test question"
        required: true
        type: string
        default: "What is the capital of France?"

jobs:
  test-notion-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Test Notion Page with Content
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            Create a test Notion page with complete content. Follow these exact steps:
            
            1. Search for "Claude Code" page using `mcp__notionApi__API-post-search`
            
            2. Create a new page under "Claude Code" using `mcp__notionApi__API-post-page` with this exact structure:
            
            ```json
            {
              "parent": { "page_id": "<CLAUDE_CODE_PAGE_ID>" },
              "properties": {
                "title": { 
                  "title": [{ 
                    "text": { 
                      "content": "Test Page - Content Creation" 
                    } 
                  }] 
                }
              },
              "children": [
                {
                  "object": "block",
                  "type": "heading_1",
                  "heading_1": {
                    "rich_text": [{
                      "type": "text",
                      "text": {
                        "content": "Test Page - Content Creation"
                      }
                    }]
                  }
                },
                {
                  "object": "block",
                  "type": "heading_2",
                  "heading_2": {
                    "rich_text": [{
                      "type": "text",
                      "text": {
                        "content": "Question"
                      }
                    }]
                  }
                },
                {
                  "object": "block",
                  "type": "paragraph",
                  "paragraph": {
                    "rich_text": [{
                      "type": "text",
                      "text": {
                        "content": "${{ github.event.inputs.test_question }}"
                      }
                    }]
                  }
                },
                {
                  "object": "block",
                  "type": "heading_2",
                  "heading_2": {
                    "rich_text": [{
                      "type": "text",
                      "text": {
                        "content": "Answer"
                      }
                    }]
                  }
                },
                {
                  "object": "block",
                  "type": "paragraph",
                  "paragraph": {
                    "rich_text": [{
                      "type": "text",
                      "text": {
                        "content": "Paris is the capital of France. It is known as the City of Light and is famous for landmarks like the Eiffel Tower, Louvre Museum, and Notre-Dame Cathedral."
                      }
                    }]
                  }
                },
                {
                  "object": "block",
                  "type": "heading_2",
                  "heading_2": {
                    "rich_text": [{
                      "type": "text",
                      "text": {
                        "content": "Metadata"
                      }
                    }]
                  }
                },
                {
                  "object": "block",
                  "type": "bulleted_list_item",
                  "bulleted_list_item": {
                    "rich_text": [{
                      "type": "text",
                      "text": {
                        "content": "Created: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
                      }
                    }]
                  }
                },
                {
                  "object": "block",
                  "type": "bulleted_list_item",
                  "bulleted_list_item": {
                    "rich_text": [{
                      "type": "text",
                      "text": {
                        "content": "Type: Test Content Creation"
                      }
                    }]
                  }
                },
                {
                  "object": "block",
                  "type": "bulleted_list_item",
                  "bulleted_list_item": {
                    "rich_text": [{
                      "type": "text",
                      "text": {
                        "content": "Status: Success if you see this content!"
                      }
                    }]
                  }
                }
              ]
            }
            ```
            
            3. Report:
               - Was the page created successfully?
               - Include the page URL
               - Any errors encountered
               
            IMPORTANT: The `children` array must be included in the API-post-page call, NOT as a separate API call.
          
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic_model: "claude-3-5-sonnet-20241022"
          allowed_tools: "mcp__notionApi__API-post-search,mcp__notionApi__API-post-page,Write"
          mcp_config: |
            {
              "mcpServers": {
                "notionApi": {
                  "command": "npx",
                  "args": ["-y", "@notionhq/notion-mcp-server"],
                  "env": { 
                    "OPENAPI_MCP_HEADERS": "{\"Authorization\":\"Bearer ${{ secrets.NOTION_KEY }}\",\"Notion-Version\":\"2022-06-28\"}"
                  }
                }
              }
            }
          max_turns: 10
          claude_env: |
            ANTHROPIC_PROMPT_CACHING=1
            CLAUDE_CODE_AUTORUN_TOOLS=true
            CLAUDE_CODE_THINKING=false
            CLAUDE_CODE_DANGEROUSLY_SKIP_PERMISSIONS=true