name: Test Notion Direct API

on:
  workflow_dispatch:

jobs:
  test-notion-api:
    runs-on: ubuntu-latest
    steps:
      - name: Test Notion API Key Directly
        env:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
        run: |
          echo "Testing Notion API key..."
          
          # Test 1: Get current user
          echo "1. Testing user endpoint..."
          USER_RESPONSE=$(curl -s -X GET 'https://api.notion.com/v1/users/me' \
            -H "Authorization: Bearer $NOTION_KEY" \
            -H "Notion-Version: 2022-06-28")
          
          echo "User response: $USER_RESPONSE"
          
          if echo "$USER_RESPONSE" | jq -e '.object == "user"' > /dev/null 2>&1; then
            echo "✅ API Key is valid!"
            echo "User type: $(echo "$USER_RESPONSE" | jq -r '.type')"
            echo "User name: $(echo "$USER_RESPONSE" | jq -r '.name // "N/A"')"
          else
            echo "❌ API Key validation failed"
            exit 1
          fi
          
          # Test 2: Search for pages
          echo -e "\n2. Searching for pages..."
          SEARCH_RESPONSE=$(curl -s -X POST 'https://api.notion.com/v1/search' \
            -H "Authorization: Bearer $NOTION_KEY" \
            -H "Notion-Version: 2022-06-28" \
            -H "Content-Type: application/json" \
            -d '{
              "query": "Claude Code",
              "filter": {
                "value": "page",
                "property": "object"
              }
            }')
          
          echo "Search response: $SEARCH_RESPONSE"
          RESULTS_COUNT=$(echo "$SEARCH_RESPONSE" | jq -r '.results | length')
          echo "Found $RESULTS_COUNT pages matching 'Claude Code'"
          
          # Test 3: Create a test page
          echo -e "\n3. Creating a test page..."
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          
          CREATE_RESPONSE=$(curl -s -X POST 'https://api.notion.com/v1/pages' \
            -H "Authorization: Bearer $NOTION_KEY" \
            -H "Notion-Version: 2022-06-28" \
            -H "Content-Type: application/json" \
            -d "{
              \"parent\": {
                \"type\": \"workspace\",
                \"workspace\": true
              },
              \"properties\": {
                \"title\": {
                  \"title\": [
                    {
                      \"text\": {
                        \"content\": \"API Test Page - $TIMESTAMP\"
                      }
                    }
                  ]
                }
              },
              \"children\": [
                {
                  \"object\": \"block\",
                  \"type\": \"paragraph\",
                  \"paragraph\": {
                    \"rich_text\": [
                      {
                        \"type\": \"text\",
                        \"text\": {
                          \"content\": \"This page was created directly via Notion API to test the API key.\"
                        }
                      }
                    ]
                  }
                },
                {
                  \"object\": \"block\",
                  \"type\": \"heading_2\",
                  \"heading_2\": {
                    \"rich_text\": [
                      {
                        \"type\": \"text\",
                        \"text\": {
                          \"content\": \"Test Information\"
                        }
                      }
                    ]
                  }
                },
                {
                  \"object\": \"block\",
                  \"type\": \"bulleted_list_item\",
                  \"bulleted_list_item\": {
                    \"rich_text\": [
                      {
                        \"type\": \"text\",
                        \"text\": {
                          \"content\": \"Created at: $TIMESTAMP\"
                        }
                      }
                    ]
                  }
                },
                {
                  \"object\": \"block\",
                  \"type\": \"bulleted_list_item\",
                  \"bulleted_list_item\": {
                    \"rich_text\": [
                      {
                        \"type\": \"text\",
                        \"text\": {
                          \"content\": \"API Key Status: ✅ Working\"
                        }
                      }
                    ]
                  }
                },
                {
                  \"object\": \"block\",
                  \"type\": \"bulleted_list_item\",
                  \"bulleted_list_item\": {
                    \"rich_text\": [
                      {
                        \"type\": \"text\",
                        \"text\": {
                          \"content\": \"Created by: GitHub Actions Direct API Test\"
                        }
                      }
                    ]
                  }
                }
              ]
            }")
          
          if echo "$CREATE_RESPONSE" | jq -e '.object == "page"' > /dev/null 2>&1; then
            echo "✅ Page created successfully!"
            PAGE_ID=$(echo "$CREATE_RESPONSE" | jq -r '.id')
            PAGE_URL=$(echo "$CREATE_RESPONSE" | jq -r '.url')
            echo "Page ID: $PAGE_ID"
            echo "Page URL: $PAGE_URL"
            echo -e "\n🎉 All tests passed! Your Notion API key is working correctly."
          else
            echo "❌ Failed to create page"
            echo "Error: $CREATE_RESPONSE"
            exit 1
          fi