name: Test Notion Simple

on:
  workflow_dispatch:

jobs:
  test-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create outputs directory
        run: mkdir -p outputs
      
      - name: Run Claude Code with Notion Test
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            Test Notion MCP by searching for "Claude Code":
            1. Use mcp__notionApi__API-post-search with query "Claude Code"
            2. Save the result to outputs/notion-test.txt
            Do NOT try to create pages or do anything else.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic_model: "claude-3-5-sonnet-20241022"
          allowed_tools: "mcp__notionApi__API-post-search,Write"
          mcp_config: |
            {
              "mcpServers": {
                "notionApi": {
                  "command": "npx",
                  "args": ["-y","@notionhq/notion-mcp-server"],
                  "env": { 
                    "OPENAPI_MCP_HEADERS": "{\"Authorization\":\"Bearer ${{ secrets.NOTION_KEY }}\",\"Notion-Version\":\"2022-06-28\"}"
                  }
                }
              }
            }
          max_turns: 5
          claude_env: |
            ANTHROPIC_PROMPT_CACHING=1
            CLAUDE_CODE_AUTORUN_TOOLS=true
            CLAUDE_CODE_THINKING=false
            CLAUDE_CODE_DANGEROUSLY_SKIP_PERMISSIONS=true
      
      - name: Display Results
        if: always()
        run: |
          echo "=== Test Results ==="
          if [ -f "outputs/notion-test.txt" ]; then
            cat outputs/notion-test.txt
          else
            echo "No test results file found"
          fi