name: Test Notion Q&A Save

on:
  workflow_dispatch:
    inputs:
      test_question:
        description: "Test question to save"
        required: true
        type: string
        default: "What is the capital of France?"

jobs:
  test-qa-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Test Q&A Saving to Claude Code Page
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            Save this Q&A session to Notion following these exact steps:
            
            User Question: "${{ github.event.inputs.test_question }}"
            
            1. Search for a page titled "Claude Code" using mcp__notionApi__API-post-search
            
            2. If found, create a new sub-page with:
               Title: Create a simple, clear title from the question
               - Remove special characters
               - Keep under 50 chars
               - Make it descriptive
               
            3. Add content blocks:
               - Heading 1: The clean title
               - Heading 2: "Question"
               - Paragraph: "${{ github.event.inputs.test_question }}"
               - Heading 2: "Answer"
               - Paragraph: "Paris is the capital of France."
               - Heading 2: "Metadata"
               - Bulleted list with:
                 * Timestamp: $(date)
                 * Test Type: GitHub Action Test
                 * Model: claude-3-5-sonnet
            
            4. Report:
               - Whether Claude Code page was found
               - The new page URL
               - Any errors
            
            Your answer to the question: Paris is the capital of France.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic_model: "claude-3-5-sonnet-20241022"
          allowed_tools: "mcp__notionApi__API-post-search,mcp__notionApi__API-post-page,mcp__notionApi__API-patch-block-children,Write"
          mcp_config: |
            {
              "mcpServers": {
                "notionApi": {
                  "command": "npx",
                  "args": ["-y","@notionhq/notion-mcp-server"],
                  "env": { 
                    "OPENAPI_MCP_HEADERS": "{\"Authorization\":\"Bearer ${{ secrets.NOTION_KEY }}\",\"Notion-Version\":\"2022-06-28\"}"
                  }
                }
              }
            }
          max_turns: 10
          claude_env: |
            ANTHROPIC_PROMPT_CACHING=1
            CLAUDE_CODE_AUTORUN_TOOLS=true
            CLAUDE_CODE_THINKING=false
            CLAUDE_CODE_DANGEROUSLY_SKIP_PERMISSIONS=true