name: Test Notion with Parent Page

on:
  workflow_dispatch:
    inputs:
      parent_page_id:
        description: "Parent page ID (optional - will search for one if not provided)"
        required: false
        type: string

jobs:
  test-notion-with-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Find or Create Parent Page
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: |
            Help me create a test page in Notion. Follow these steps:
            
            1. First, use mcp__notionApi__API-get-users to list all users and find the workspace info
            
            2. Use mcp__notionApi__API-post-search to search for ANY existing page (don't filter by name)
               - If you find any pages, use the first one as parent
               - Note the page ID and title
            
            3. If a parent page ID was provided: "${{ github.event.inputs.parent_page_id }}"
               - Use that as the parent instead
            
            4. Create a new page under the parent with:
               - Title: "Claude Code Test - $(date)"
               - Content blocks:
                 - Paragraph: "This test page was created by Claude Code GitHub Action"
                 - Heading 2: "Test Results"
                 - Bulleted list with:
                   - "✅ Notion API Key: Working"
                   - "✅ MCP Integration: Connected"
                   - "✅ Page Creation: Successful"
                   - "Created at: [current timestamp]"
            
            5. After creating the page, create a sub-page under it called "Claude Code Q&A Sessions"
               - This will be the parent for future Q&A saves
            
            Report:
            - Parent page used (ID and title)
            - Created page URL
            - Sub-page URL
            - Any errors encountered
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          anthropic_model: "claude-3-5-sonnet-20241022"
          allowed_tools: "mcp__notionApi__API-get-users,mcp__notionApi__API-post-search,mcp__notionApi__API-post-page,mcp__notionApi__API-patch-block-children,mcp__notionApi__API-retrieve-a-page"
          mcp_config: |
            {
              "mcpServers": {
                "notionApi": {
                  "command": "npx",
                  "args": ["-y","@notionhq/notion-mcp-server"],
                  "env": { 
                    "OPENAPI_MCP_HEADERS": "{\"Authorization\":\"Bearer ${{ secrets.NOTION_KEY }}\",\"Notion-Version\":\"2022-06-28\"}"
                  }
                }
              }
            }
          max_turns: 15
          claude_env: |
            ANTHROPIC_PROMPT_CACHING=1
            CLAUDE_CODE_AUTORUN_TOOLS=true
            CLAUDE_CODE_THINKING=false
            CLAUDE_CODE_DANGEROUSLY_SKIP_PERMISSIONS=true